version: '1.0'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql